name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: "64.227.135.20"
          key: ${{secrets.SSH_KEY}}
          username: root
          script: |
            mkdir /var/www/vhosts/test
            git pull https://github.com/VijayKadiyam/test-droplet.git
            echo 'Deployment Done'
            echo ${{secrets.SSH_HOST}}
        
      
          
